// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

final class Particle extends ffi.Struct {
  @ffi.Double()
  external double mass;

  @ffi.Double()
  external double pos_x;

  @ffi.Double()
  external double pos_y;

  @ffi.Double()
  external double vel_x;

  @ffi.Double()
  external double vel_y;

  @ffi.Double()
  external double force;
}

@ffi.Native<
    ffi.Void Function(
        ffi.Int32, ffi.Double, ffi.Double, ffi.Double, ffi.Double)>()
external void init_c(
  int particles_amount,
  double canvas_width,
  double canvas_height,
  double min_mass,
  double max_mass,
);

@ffi.Native<ffi.Pointer<Particle> Function()>()
external ffi.Pointer<Particle> update_particles_c();
