// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

@ffi.Native<
    ffi.Pointer<NBody> Function(ffi.Int, ffi.Float, ffi.Float, ffi.Float,
        ffi.Float, ffi.Pointer<NBody>)>()
external ffi.Pointer<NBody> init(
  int particles_amount,
  double canvas_width,
  double canvas_height,
  double min_mass,
  double max_mass,
  ffi.Pointer<NBody> previous_ptr,
);

@ffi.Native<ffi.Pointer<ParticleRust> Function(ffi.Pointer<NBody>)>()
external ffi.Pointer<ParticleRust> update_particles(
  ffi.Pointer<NBody> n_body_ptr,
);

final class NBody extends ffi.Opaque {}

final class ParticleRust extends ffi.Struct {
  @ffi.Float()
  external double mass;

  @ffi.Float()
  external double pos_x;

  @ffi.Float()
  external double pos_y;

  @ffi.Float()
  external double vel_x;

  @ffi.Float()
  external double vel_y;

  @ffi.Float()
  external double force;
}
